import React, { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import { useFarm } from '../context/FarmContext';
import { CheckCircle2, ExternalLink, MapPin, Navigation, Save, ShieldCheck, UserRound } from 'lucide-react';

export const MitraProfilePage:React.FC=()=>{
 const {currentUser,showToast}=useFarm(); const [partner,setPartner]=useState<any>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [gps,setGps]=useState(false);
 const [form,setForm]=useState<any>({address:'',province:'',regency:'',district:'',village:'',latitude:null,longitude:null});
 const load=async()=>{try{setLoading(true);const r=await api.getMitraProfile();const p=r.partner||{};setPartner(p);setForm({address:p.address||'',province:p.province||'',regency:p.regency||'',district:p.district||'',village:p.village||'',latitude:p.latitude??null,longitude:p.longitude??null})}catch(e:any){showToast(e?.message||'Gagal memuat profil Mitra.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const complete=useMemo(()=>Boolean(form.address&&form.province&&form.regency&&form.district&&form.village&&form.latitude!=null&&form.longitude!=null),[form]);
 const takeGps=()=>{if(!navigator.geolocation)return showToast('Browser tidak mendukung GPS.');setGps(true);navigator.geolocation.getCurrentPosition(pos=>{setForm((x:any)=>({...x,latitude:Number(pos.coords.latitude.toFixed(7)),longitude:Number(pos.coords.longitude.toFixed(7))}));setGps(false);showToast('Lokasi basecamp berhasil diambil.')},()=>{setGps(false);showToast('Gagal mengambil GPS. Aktifkan izin lokasi browser.')},{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(form.latitude==null||form.longitude==null)return showToast('Ambil titik GPS basecamp terlebih dahulu.');try{setSaving(true);const r=await api.updateMitraProfile({...form,latitude:Number(form.latitude),longitude:Number(form.longitude)});setPartner(r.partner);showToast(r.message||'Profil Mitra berhasil disimpan.')}catch(err:any){showToast(err?.message||'Gagal menyimpan profil.')}finally{setSaving(false)}};
 const mapUrl=form.latitude!=null&&form.longitude!=null?`https://www.google.com/maps?q=${form.latitude},${form.longitude}`:'';
 return <div className="space-y-6 pb-10">
  <div><span className="px-3 py-1 rounded-full bg-[#EAF2EC] border border-[#CDE3D3] text-xs font-black">IDENTITAS MITRA</span><h1 className="text-3xl md:text-4xl font-black mt-2 font-['Outfit']">Profil Mitra</h1><p className="text-sm text-stone-500 mt-1">Alamat basecamp, wilayah dan titik Maps/GPS operasional.</p></div>
  {loading?<div className="py-12 text-center font-bold text-stone-400">Memuat profil...</div>:<>
   <div className="bg-[#1B3022] text-white rounded-3xl p-5 md:p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-white/10 flex items-center justify-center"><UserRound className="w-7 h-7 text-[#D4AF37]"/></div><div><div className="text-[10px] text-[#D4AF37] font-black uppercase">Mitra Pendamping</div><h2 className="font-black text-xl">{partner?.name||currentUser?.fullName}</h2><div className="text-xs text-white/65 font-mono mt-1">{partner?.partner_code||partner?.partnerCode||currentUser?.partnerCode}</div></div></div><div className={`px-3 py-2 rounded-xl text-xs font-black border ${complete?'bg-emerald-500/10 border-emerald-400/30 text-emerald-200':'bg-amber-500/10 border-amber-400/30 text-amber-200'}`}>{complete?'PROFIL LENGKAP':'PERLU DILENGKAPI'}</div></div>
   <form onSubmit={save} className="bg-white border border-[#EFECE6] rounded-3xl p-5 md:p-6 space-y-4"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-[#2D4A36]"/><h2 className="font-black text-xl">Data Basecamp</h2></div><div className="grid sm:grid-cols-2 gap-3"><input value={form.province} onChange={e=>setForm({...form,province:e.target.value})} placeholder="Provinsi *" required className="p-3 rounded-2xl border"/><input value={form.regency} onChange={e=>setForm({...form,regency:e.target.value})} placeholder="Kabupaten/Kota *" required className="p-3 rounded-2xl border"/><input value={form.district} onChange={e=>setForm({...form,district:e.target.value})} placeholder="Kecamatan *" required className="p-3 rounded-2xl border"/><input value={form.village} onChange={e=>setForm({...form,village:e.target.value})} placeholder="Desa/Kelurahan *" required className="p-3 rounded-2xl border"/></div><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} rows={3} placeholder="Alamat Basecamp Lengkap *" required className="w-full p-3 rounded-2xl border"/>
    <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-3xl bg-[#FAF7F2] border border-[#EFECE6] p-4"><div className="font-black flex items-center gap-2"><MapPin className="w-5 h-5"/>Titik Maps Basecamp</div><button type="button" onClick={takeGps} disabled={gps} className="mt-3 w-full p-3 rounded-2xl bg-[#1B3022] text-white font-black flex items-center justify-center gap-2"><Navigation className="w-4 h-4"/>{gps?'Mengambil Lokasi...':'Gunakan Lokasi Saya'}</button>{form.latitude!=null&&form.longitude!=null&&<><div className="mt-3 p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-xs font-bold text-emerald-700 flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>GPS tersimpan: {form.latitude}, {form.longitude}</div><a href={mapUrl} target="_blank" rel="noreferrer" className="mt-2 w-full p-3 rounded-xl border bg-white font-bold text-sm flex items-center justify-center gap-2"><ExternalLink className="w-4 h-4"/>Buka Google Maps</a></>}</div><div className="rounded-3xl overflow-hidden border min-h-[240px] bg-stone-50">{mapUrl?<iframe title="Lokasi Basecamp" src={`https://maps.google.com/maps?q=${form.latitude},${form.longitude}&z=16&output=embed`} className="w-full h-[260px] border-0"/>:<div className="h-[240px] flex items-center justify-center text-stone-400 text-sm">Maps tampil setelah GPS diambil.</div>}</div></div>
    <button disabled={saving} className="px-6 py-3 rounded-2xl bg-[#D4AF37] text-[#1B3022] font-black flex items-center gap-2"><Save className="w-4 h-4"/>{saving?'Menyimpan...':'Simpan Profil Mitra'}</button>
   </form>
  </>}
 </div>;
};
export default MitraProfilePage;
